### ISSUE TITLE
Error while generating training split, using datasets library

### ISSUE THREAD

**Issue by mung3477** [Zdong104/FNSPID_Financial_News_Dataset#2]
Hello, I am trying to use your dataset for my personal project.
While trying to use FNSPID dataset with `datasets` library, the error below occurred.
Could you review your code and data? 
Thank you for reading. I'll look forward to new updates!

![image.png](https://cdn-uploads.huggingface.co/production/uploads/65c474a89f6c4689fbb99b6d/naLN6MJdwq6Rg1rsVVR1w.png)

**Comment by Zdong104** [comment]
Hi @mung3477 since users experienced the issue for dataset is too large, we uploaded additional files to the dataset. when you load the dataset you might need to check which one is the best work for you. 
If you need additional help. Please let me know by email, we can schedule a call to help you address this issue.

**Comment by forefab** [comment]
This error is still unsolved, it even shows up on the hugging dataset preview:
<img width="1024" alt="image" src="https://github.com/Zdong104/FNSPID_Financial_News_Dataset/assets/128795514/9707bc23-cf73-4c97-9911-25d8a33ff10d">

What's the workaround for loading the data?

**Comment by ManasTrip** [comment]
Error keeps occuring, any work around?

**Comment by ManasTrip** [comment]
@forefab as mentioned above they have uploaded all the csvs in the huggingface repo , you can choose which files you want to download :[https://huggingface.co/datasets/Zihan1004/FNSPID/tree/main]
